### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by hsmurali** [jermp/fulgor#17]
![Screenshot 2023-09-12 at 1 48 18 PM](https://github.com/jermp/fulgor/assets/42724690/db1a426b-8196-45d5-b72d-c26fc1131492)

I get this error when I try to build fulgor. It works when I compile it with “-**mpopcnt**” flag. Would it be possible to make a commit with “-**mpopcnt**” flag in the CMakeLists.txt? 

I am using FULGOR in one of my projects and it would be easier to integrate it into my pipeline if the flag was added to the CMakeLists. 

Thank you.

**Comment by jermp** [comment]
Hi @hsmurali,
sure, we're here to help. Where exactly did you add it?
Did you add it here?

    # Flags for PTHash:
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mbmi2 -msse4.2") # for hardware popcount and pdep

It's strange you got that error because the `-msse4.2` should cover popcount.

**Comment by hsmurali** [comment]
Thank you. Yes that is where I added the -mpopcnt flag.

**Comment by jermp** [comment]
Ok, added. Can you test it on your end now to confirm it works correctly?
Thanks!

**Comment by hsmurali** [comment]
Thanks, works fine now! I'll close the issue
