### ISSUE TITLE
Fulgor Indexing Error Due to Empty Bucket Detection

### ISSUE THREAD

**Issue by Francii-B** [jermp/fulgor#31]
Hi @jermp !!

@karel-brinda and I are using Fulgor to build indexes of bacterial collections, but we're running into the same issue mentioned in https://github.com/COMBINE-lab/simpleaf/issues/126 (i.e. the indexing process gets aborted due to the detection of an empty bucket). We saw that you fixed this in sshash (https://github.com/jermp/sshash/issues/42), but Fulgor is still referring to its older version. Would it be possible to integrate those fixes into Fulgor?

Here's the error message I get when I run the `fulgor build` command:
```
=== step 3: 'build_index' 1.51034 [sec] (28.1915 [ns/kmer])
max_num_super_kmers_in_bucket 4121
max_num_super_kmers_in_bucket 4121
log2_max_num_super_kmers_in_bucket 13
num_buckets_in_skew_index 92/8799835(0.00104547%)
num_partitions 7
computing partitions...
num_kmers belonging to buckets of size > 64 and <= 128: 16574
num_kmers belonging to buckets of size > 128 and <= 256: 7551
num_kmers belonging to buckets of size > 256 and <= 512: 3626
num_kmers belonging to buckets of size > 512 and <= 1024: 3374
num_kmers belonging to buckets of size > 1024 and <= 2048: 6119
==> Empty bucket detected:
there is no list of size > 2048 and <= 4096
terminate called after throwing an instance of 'sshash::empty_bucket_runtime_error'
  what():  try a different choice of l or change seed
/usr/bin/bash: line 1: 83654 Aborted 
```

Thank you in advance!!

**Comment by jermp** [comment]
Ciao @Francii-B!

As of 54244933aa096d6d8931a8f40b1df36ec4b26aae, this is now done. Thank you for pointing this out.

Let me know if this now works for you.
