### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by Sudaraka88** [jermp/fulgor#32]
Hi, Thank you for creating fulgor., looking forward to using it! 

Apologies for raising this here because the first part of this is an issue in the kmeans dependency.

I was trying to install fulgor yesterday and ran into this error:
```
.../fulgor/./external/kmeans/include/kmeans.hpp: In function ‘std::vector<float> kmeans::details::closest_distance(const std::vector<std::vector<float> >&, RandomAccessIterator, RandomAccessIterator)’:
.../fulgor/./external/kmeans/include/kmeans.hpp:45:5: error: invalid controlling predicate
     for (uint64_t i = 0; i != num_points; ++i) {
     ^~~
```

```
.../fulgor/./external/kmeans/include/kmeans.hpp: In function ‘std::vector<unsigned int> kmeans::details::calculate_clusters(RandomAccessIterator, RandomAccessIterator, const std::vector<std::vector<float> >&)’:
.../fulgor/./external/kmeans/include/kmeans.hpp:134:5: error: invalid controlling predicate
     for (uint64_t i = 0; i != num_points; ++i) {
     ^~~
```

I found the explanation here: https://stackoverflow.com/questions/33493215/openmp-error-invalid-controlling-predicate
I just replaced != with <, which got it working. 

Also, there was a problem in the linking step:

```
CMakeFiles/fulgor.dir/tools/fulgor.cpp.o: In function build(int, char**)':
/usr/include/c++/8/bits/fs_path.h:185: undefined reference to std::filesystem::__cxx11::path::_M_split_cmpts()'
CMakeFiles/fulgor.dir/tools/fulgor.cpp.o: In function build(int, char**)':
/usr/include/c++/8/bits/fs_ops.h:121: undefined reference to std::filesystem::status(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fulgor.dir/build.make:101: fulgor] Error 1
make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/fulgor.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

I added `stdc++fs` in to the list of target_link_libraries in the `CMakeLists.txt`, which got things working.

My system:
Red Hat Enterprise Linux release 8.10
cmake version 3.30.1
GNU Make 4.2.1

Thanks again!

**Comment by rob-p** [comment]
Hi @Sudaraka88,

  Can you say what compiler and version you are using as well? Since we didn't run into these issues in compilation, it must be a compiler version related issue.

**Comment by Sudaraka88** [comment]
Sorry, here you go:

c++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
Copyright (C) 2018 Free Software Foundation, Inc.

I now realise my compiler is quite old, this should explain it.

**Comment by rob-p** [comment]
Right; technically, fulgor requires C++17 compatibility, which I think gcc 8.5 may not completely have.

**Comment by Sudaraka88** [comment]
I see, thanks, I will rebuild with a newer compiler...
