### ISSUE TITLE
Recommendations for reference position index

### ISSUE THREAD

**Issue by heuermh** [jermp/fulgor#39]
Sorry, more of a question than an issue:

I have had some luck with Fulgor pseudoalignment on metagenomic samples.  For hits within taxa of interest, I'd like a second pass to improve results.  The paper in _Algorithms for Molecular Biology_ mentions using an index that retains reference positions and/or issuing locate queries for all k-mers.

Might you know, what is the state of the art for this kind of index?  I wrote something naively and as might be expected it is very large on disk and difficult to work with in limited RAM situations.

**Comment by jermp** [comment]
Hello @heuermh and thank you for your question!
I'm also glad you found Fulgor useful.

> Might you know, what is the state of the art for this kind of index?

You might want to check Pufferfish2 (https://github.com/COMBINE-lab/pufferfish2), that we published in RECOMB 2023, for a kmer reference index. A similar indexe (albeit slower and somewhat larger) is MONI.

We have plans to extend Fulgor to also incorporate positional information (and kmer abundances).
This will be done in the near future but it is not happening tomorrow :)

Let me know if you have further questions.
Best,
-Giulio

**Comment by heuermh** [comment]
Great, thank you for the suggestions, @jermp!
